### ISSUE TITLE
Provide a way to set the default endpoint to something other than localhost

### ISSUE THREAD

**Issue by geekpete** [elastic/powershell#2]
Without a way to set the default endpoint, you have to specify `-Uri` or the full endpoint for each request.
A variable that can be set with some default endpoint details (Uri, creds) and be reused for subsequent requests would be great.
Ability to set this in powershell profile or other config file might be cool too.

**Comment by russcam** [comment]
The simple solution is to assign the base URI to a variable, then use this in the `Invoke-Elasticsearch` call

```powershell
$b = "https://example.com:9200"

# press <TAB> to cycle through endpoints
es "$b/"
```

Tab completion will expand `$b/` out to its value, when `-Uri` argument is double quoted.
